package io.kestra.plugin.github;

import io.kestra.core.models.property.Property;
import io.kestra.core.models.tasks.Task;
import io.kestra.core.runners.RunContext;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;
import org.kohsuke.github.GitHub;
import org.kohsuke.github.GitHubBuilder;
import io.kestra.core.models.annotations.PluginProperty;

@SuperBuilder
@ToString
@EqualsAndHashCode
@Getter
@NoArgsConstructor
public abstract class AbstractGithubTask extends Task {
    @Schema(
        title = "GitHub login",
        description = "GitHub login used with `oauthToken` for authenticated requests. Leave unset when authenticating with `jwtToken` or `appInstallationToken`."
    )
    @PluginProperty(group = "advanced")
    private Property<String> login;

    @Schema(
        title = "GitHub OAuth token",
        description = "GitHub personal access token used for authenticated requests. Can be used alone or with `login`."
    )
    @PluginProperty(group = "connection", secret = true)
    private Property<String> oauthToken;

    @Schema(
        title = "GitHub JWT token",
        description = "GitHub App JWT used for app-level authentication. Use this when the task should authenticate as the app rather than a user."
    )
    @PluginProperty(group = "connection", secret = true)
    private Property<String> jwtToken;

    @Schema(
        title = "GitHub App installation token",
        description = "Installation access token generated by a GitHub App. Use this for repository-scoped app access instead of a user token."
    )
    @PluginProperty(group = "connection", secret = true)
    private Property<String> appInstallationToken;

    @Schema(
        title = "GitHub API endpoint",
        description = "GitHub or GitHub Enterprise API base URL such as `https://api.github.com` or `https://ghe.acme.com/api/v3`. Set this when targeting GitHub Enterprise or a non-default API endpoint."
    )
    @PluginProperty(group = "connection")
    private Property<String> endpoint;

    protected Property<String> oauthTokenProperty() {
        return oauthToken;
    }

    protected Property<String> jwtTokenProperty() {
        return jwtToken;
    }

    protected Property<String> appInstallationTokenProperty() {
        return appInstallationToken;
    }

    protected GitHub connect(final RunContext runContext) throws Exception {
        GitHubBuilder builder = new GitHubBuilder();

        if (this.login != null && this.oauthToken != null) {
            builder.withOAuthToken(
                runContext.render(this.oauthToken).as(String.class).orElseThrow(),
                runContext.render(this.login).as(String.class).orElseThrow()
            );
        } else {
            runContext.render(this.oauthToken).as(String.class).ifPresent(builder::withOAuthToken);
        }

        runContext.render(this.jwtToken).as(String.class).ifPresent(builder::withJwtToken);
        runContext.render(this.appInstallationToken).as(String.class).ifPresent(builder::withAppInstallationToken);
        runContext.render(this.endpoint).as(String.class).ifPresent(builder::withEndpoint);

        return builder.build();
    }
}
