package io.kestra.plugin.github;

import io.kestra.core.models.property.Property;
import io.kestra.core.models.tasks.Task;
import io.kestra.core.runners.RunContext;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;
import org.kohsuke.github.GitHub;
import org.kohsuke.github.GitHubBuilder;

@SuperBuilder
@ToString
@EqualsAndHashCode
@Getter
@NoArgsConstructor
public abstract class AbstractGithubTask extends Task {
    @Schema(
        title = "GitHub login",
        description = "Requires additional field: oauthToken, to log-in"
    )
    private Property<String> login;

    @Schema(
        title = "GitHub oauthToken",
        description = "GitHub Personal Access Token. In addition, can be used with login or by its own"
    )
    private Property<String> oauthToken;

    @Schema(
        title = "GitHub JWT token",
        description = "Does not requires additional fields to log-in"
    )
    private Property<String> jwtToken;

    @Schema(
        title = "GitHub Installation Token generated by the GitHub Application."
    )
    private Property<String> appInstallationToken;

    @Schema(
        title = "The URL of GitHub (or GitHub enterprise) API endpoint",
        description = "The URL of GitHub (or GitHub enterprise) API endpoint, such as ``https://api.github.com` or `https://ghe.acme.com/api/v3`. Note that GitHub Enterprise has /api/v3 in the URL."
    )
    private Property<String> endpoint;

    protected GitHub connect(final RunContext runContext) throws Exception {
        GitHubBuilder builder = new GitHubBuilder();

        if (this.login != null && this.oauthToken != null) {
            builder.withOAuthToken(
                runContext.render(this.oauthToken).as(String.class).orElseThrow(),
                runContext.render(this.login).as(String.class).orElseThrow()
            );
        } else {
            runContext.render(this.oauthToken).as(String.class).ifPresent(builder::withOAuthToken);
        }

        runContext.render(this.jwtToken).as(String.class).ifPresent(builder::withJwtToken);
        runContext.render(this.appInstallationToken).as(String.class).ifPresent(builder::withAppInstallationToken);
        runContext.render(this.endpoint).as(String.class).ifPresent(builder::withEndpoint);

        return builder.build();
    }
}
